<h1>Torch Tensors</h1>

##  Tensors

- In Pytorch, Tensors are the building blocks of neural network.
- A  tensor is a single or multidimensional array of a single data type.
   - A 1-dimensional tensor is often called a vector
   - A 2-dimensional tensor is often called a matrix
   - Tensors with a higher dimension are generally  called a tensor
- Tensors have different types and shapes
- The input, output and parameters of a Neural Network are tensors.
- When processing the input, a neural network  applies a series of tensor operations on the data it receives.

## Useful links
[Pytorch Tutorial](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)


### Tensor Basics

- Creating Tensors
- Types and Shape
- Indexing and Slicing
- Tensor Functions
- Tensor Operations

#### Libraries

In [3]:
# These are the libraries will be used for this lab.

import torch 
import numpy as np 
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline  

Check PyTorch version:


In [4]:
torch.__version__

'2.5.1+cu121'

This is a function for plotting diagrams. You will use this function to plot the vectors in Coordinate system.


In [3]:
# Plot vecotrs, please keep the parameters in the same length
# @param: Vectors = [{"vector": vector variable, "name": name of vector, "color": color of the vector on diagram}]
    
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

<!--Empty Space for separating topics-->


## Creating Tensors

**Creating a tensors from a list of integers** using the constructor <code>torch.tensor()</code>

In [63]:
# Convert a integer list with length 5 to a tensor
t = torch.tensor([0, 1, 2, 3, 4])
t

tensor([0, 1, 2, 3, 4])

In [44]:
# Convert 2D List to 2D Tensor
l = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
torch.tensor(l)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

**Creating a tensor from a <b>numpy</b> array</b>** using the constructor <code>torch.from_numpy()</code>

In [48]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
t = torch.from_numpy(numpy_array)

print("Dtype: ", t.dtype)
print("Type: ", t.type())

Dtype:  torch.float64
Type:  torch.DoubleTensor


In [51]:
# Convert tensor to numpy array; Convert numpy array to tensor

a = t.numpy()
print("The numpy array: ", a)
print("Type: ", a.dtype)

t = torch.from_numpy(a)
print("Tensor:", t)
print("Type: ", t.dtype)

The numpy array:  [0. 0. 0. 0. 0.]
Type:  float64
Tensor: tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
Type:  torch.float64


**Converting a tensor to a numpy array.**

In [49]:
# Convert a tensor to a numpy array
back_to_numpy = new_tensor.numpy()
print("Numpy Array: ", back_to_numpy)
print("Dtype: ", back_to_numpy.dtype)

Numpy Array:  [[ 11  12]
 [ 21  22]
 [ 31 312]]
Dtype:  int64


back_to_numpy and new_tensor still point to numpy_array. As a result if we change numpy_array both back_to_numpy and new_tensor will change. For example if we set all the elements in numpy_array to zeros, back_to_numpy and  new_tensor will follow suit.

In [50]:
numpy_array[:] = 0
print("The new tensor points to numpy_array : ", new_tensor) 
print("and back to numpy array points to the tensor: ", back_to_numpy)

The new tensor points to numpy_array :  tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
and back to numpy array points to the tensor:  [[ 11  12]
 [ 21  22]
 [ 31 312]]


**Convert a panda series to a tensor** using pandas `values` and `torch.from_numpy`

In [53]:
# Convert a panda series to a tensor
pandas_series=pd.Series([0.1, 2, 0.3, 10.1])
new_tensor=torch.from_numpy(pandas_series.values)
print("Tensor: ", new_tensor)
print("Dtype: ", new_tensor.dtype)
print("Type: ", new_tensor.type())

Tensor:  tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
Dtype:  torch.float64
Type:  torch.DoubleTensor


In [ ]:
# Convert the Panda Dataframe to tensor
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})

print("Numpy array: ", df.values)
print("DType: ", df.values.dtype)

print("================================================")

new_tensor = torch.from_numpy(df.values)
print("Tensor: ", new_tensor)
print("DType ", new_tensor.dtype)

In [52]:
# Convert the Panda Dataframe to tensor
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})

print("Numpy array: ", df.values)
print("DType: ", df.values.dtype)

print("================================================")

new_tensor = torch.from_numpy(df.values)
print("Tensor: ", new_tensor)
print("DType ", new_tensor.dtype)

Numpy array:  [[ 11  12]
 [ 21  22]
 [ 31 312]]
DType:  int64
Tensor:  tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
DType  torch.int64


**Converting a tensor to a list** using the `tolist()` method

In [47]:
torch_to_list=this_tensor.tolist()

print('tensor:', this_tensor,"\nlist:",torch_to_list)

tensor: tensor([0, 1, 2, 3]) 
list: [0, 1, 2, 3]


**Creating a tensor for a given dimension and filling it with random numbers**

In [4]:
t = torch.randn(3, 4, 2)
t, t.numel()

(tensor([[[ 0.9898,  1.0487],
          [ 0.6919, -1.2918],
          [ 1.9365,  0.2000],
          [-1.9984, -0.2465]],
 
         [[-0.6709,  0.1321],
          [-1.4870,  1.5448],
          [-0.3092,  0.2954],
          [-0.7122, -0.9132]],
 
         [[-0.3964,  0.3051],
          [-0.5807, -1.3194],
          [-1.7276, -1.3876],
          [-0.8279,  1.0017]]]),
 24)

**Construct a matrix filled with zeros and of dtype long (=integers)**

In [5]:
# Construct a matrix (5 rows, 3 columns) filled with zeros and of dtype long (=integers):
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<!--Empty Space for separate topics-->


## Types of Tensors

[Tensor Types in Pytorch](https://pytorch.org/docs/stable/tensors.html)

The type of a tensor `tensor.type()` depends on the data type `tensor.dtype()` of the elements in the tensor.

<img src="images/tensor-types.png" width="100%"/>

In [85]:
t = torch.tensor([0, 1, 2, 3, 4])

# Print out 
print("DType: ", t.dtype)
print("Tensor type:", t.type())

DType:  torch.int64
Tensor type: torch.LongTensor


In [86]:
t = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
print("Data type:", t.dtype)
print("Tensor type:", t.type())

Data type: torch.float32
Tensor type: torch.FloatTensor


**From a list of floats to a tensor of integers**

In [87]:
list_floats=[0.0, 1.0, 2.0, 3.0, 4.0]
# Create a tensor of integers from a list of floats
tensor=torch.tensor(list_floats,dtype=torch.int64)

print("Dtype: ", floats_int_tensor.dtype)
print("Tensor type: ", floats_int_tensor.type())

Dtype:  torch.int64
Tensor type:  torch.LongTensor


<!--Empty Space for separating topics-->


**From a list of integers to a tensor of floats**

In [88]:
# Create a tensor of floats from a list of integers 
t = torch.FloatTensor([0, 1, 2, 3, 4])
print("Dtype:",t.dtype)
print("Tensor type:",t.type())

Dtype: torch.float32
Tensor type: torch.FloatTensor


**Converting an existing tensor object to another tensor type**

In [29]:
int_tensor = torch.tensor([0, 1, 2, 3, 4])
float_tensor = int_tensor.type(torch.FloatTensor)
print("Tensor type:", float_tensor.type())

Tensor type: torch.FloatTensor


<!--Empty Space for separating topics-->


## Tensors Size (or Shape), Number of dimensions and Number of Elements

- Use <code><i>tensor_obj</i>.size()</code> to find out the size of a <code><i>tensor_obj</i></code>.
- Use <code><i>tensor_obj</i>.ndimension()</code> to show its dimension

In [37]:
# One-dimensional tensor object with 5 columns/elements
t = torch.tensor([0, 1, 2, 3, 4])
print("Size: ", t.size())
print("Shape: ", t.shape)
print("Dimension: ", t.ndimension()) # number of dimensions the tensor has
print('Tensor dtype: \t\t', t.dtype)       # type of the data contained within the tensor.
print('Device tensor on: \t', t.device)    # where tensor computations will be performed (CPU or GPU)
print('Tensor layout: \t\t', t.layout)     # how the tensor is stored in memory
print('Number of elements: \t', t.numel()) # number of elements contained within the tensor

Size:  torch.Size([5])
Shape:  torch.Size([5])
Dimension:  1
Tensor dtype: 		 torch.int64
Device tensor on: 	 cpu
Tensor layout: 		 torch.strided
Number of elements: 	 5


In [38]:
# 2 dimensional tensor with 2 rows and 5 columns
t = torch.tensor([[0, 1, 2, 3, 4],[0, 1, 2, 3, 4]])

print("Size: ", t.size())
print("Shape: ", tensor.shape)
print("Dimension: ", tensor.ndimension()) # number of dimensions the tensor has
print('Tensor dtype: \t\t', t.dtype)       # type of the data contained within the tensor.
print('Device tensor on: \t', t.device)    # where tensor computations will be performed (CPU or GPU)
print('Tensor layout: \t\t', t.layout)     # how the tensor is stored in memory
print('Number of elements: \t', t.numel()) # number of elements contained within the tensor

Size:  torch.Size([2, 5])
Shape:  torch.Size([2, 5])
Dimension:  2
Tensor dtype: 		 torch.int64
Device tensor on: 	 cpu
Tensor layout: 		 torch.strided
Number of elements: 	 10


<!--Empty Space for separating topics-->


## Reshaping a tensor
- Use `reshape` or `view`

In [39]:
# One-dimensional tensor object with 5 elements
tensor = torch.tensor([0, 1, 2, 3, 4])
# Two-dimensional tensor object with 5 rows and 1 column.
reshaped_tensor = tensor.view(5, 1)
print("Original Size: ", tensor.size())
print("Size after view method", reshaped_tensor.size())

Original Size:  torch.Size([5])
Size after view method torch.Size([5, 1])


If you do not know the size of your tensor, you can use <b>-1</b> to reshape it (-1 represent any size). Note that you can set only one argument as -1.

In [40]:
# One-dimensional tensor object with 5 elements
tensor = torch.tensor([0, 1, 2, 3, 4])
# Two-dimensional tensor object with 5 rows and 1 column.
reshaped_tensor = tensor.view(1, -1)
print("Original Size: ", tensor.size())
print("Size after view method", reshaped_tensor.size())

Original Size:  torch.Size([5])
Size after view method torch.Size([1, 5])


In [41]:
# Create a tensor of size (3,4) with random values
t = torch.randn(3, 4)
t, t.numel()

(tensor([[ 0.4189,  0.5255,  0.3237, -0.0530],
         [ 0.7455,  1.5780, -0.0514, -2.7680],
         [-0.3354, -0.2014,  2.2626,  2.2106]]),
 12)

In [42]:
# reshape from (3,4) to (2,6). new shape must give same numel as initial
t_26 = t.reshape([2,6])
t_26, t_26.numel()

(tensor([[ 0.4189,  0.5255,  0.3237, -0.0530,  0.7455,  1.5780],
         [-0.0514, -2.7680, -0.3354, -0.2014,  2.2626,  2.2106]]),
 12)

In [43]:
# reshape from (3,4) to (6,2)
t_62 = t.reshape([6,2])
t_62, t_62.numel()

(tensor([[ 0.4189,  0.5255],
         [ 0.3237, -0.0530],
         [ 0.7455,  1.5780],
         [-0.0514, -2.7680],
         [-0.3354, -0.2014],
         [ 2.2626,  2.2106]]),
 12)

In [ ]:
# reshape from (3,4) to (6,2)
t_62 = t.reshape([6,2])
t_62, t_62.numel()

In [ ]:
# reshape from (3,4) to (6,2)
t_62 = t.reshape([6,2])
t_62, t_62.numel()

### Squeezing and unsqueezing
* Squeezing a tensor removes the dimensions or axes that have a length of one.
* Unsqueezing a tensor adds a dimension with a length of one.
* These functions allow us to expand or shrink the rank (number of dimensions) of our tensor

In [ ]:
print(t.reshape([1,12]).shape)
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

In [ ]:
y = torch.randn(3,2,3)

In [ ]:
print(y.size())
y3 = y.unsqueeze(2)
print(y3.size())
print(y3.squeeze().size())

### Transpose

In [67]:
x = torch.randn(3,2)
y = x.transpose(0, 1)
print('X shape: ', x.shape)
print('Y shape: ', y.shape)
x, y

X shape:  torch.Size([3, 2])
Y shape:  torch.Size([2, 3])


(tensor([[ 0.7229,  0.9356],
         [-0.4960,  0.0758],
         [-0.3961, -0.2935]]),
 tensor([[ 0.7229, -0.4960, -0.3961],
         [ 0.9356,  0.0758, -0.2935]]))

In [64]:
# broadcasting
x = torch.rand(3, 1)
y = torch.rand(3, 2)
print('X shape: ', x.shape)
print('Y shape: ', y.shape) # Notice that x's dimension 1 (aka 2nd dim, aka last dim)     is of size 1, while y's is of size 2
print(x)
print(y)
print(x + y)
print(torch.equal(x+y, y+x)) # check equality of 2 tensors

X shape:  torch.Size([3, 1])
Y shape:  torch.Size([3, 2])
tensor([[0.8146],
        [0.0405],
        [0.6512]])
tensor([[0.8926, 0.4838],
        [0.1523, 0.9513],
        [0.8679, 0.3407]])
tensor([[1.7072, 1.2984],
        [0.1927, 0.9918],
        [1.5191, 0.9919]])
True


## Indexing and Slicing
- You can access the value on a certain index by using the square bracket e.g., `tensor[3]`
-  You can access parts of a tensor by using the slicing notation e.g., `tensor[1:3]`


In [95]:
# Indexing
index_tensor = torch.tensor([0, 1, 2, 3, 4])
print("The value on index 0:",index_tensor[0])
print("The value on index 1:",index_tensor[1])
print("The value on index 2:",index_tensor[2])
print("The value on index 3:",index_tensor[3])
print("The value on index 4:",index_tensor[4])

The value on index 0: tensor(0)
The value on index 1: tensor(1)
The value on index 2: tensor(2)
The value on index 3: tensor(3)
The value on index 4: tensor(4)


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2_index2.png" width="500" alt="Example of Matrix Index">


In [62]:
# Use tensor_obj[row, column] and tensor_obj[row][column] to access certain position

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[0, 0])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[0][0])

What is the value on 2nd-row 3rd-column?  tensor(11)
What is the value on 2nd-row 3rd-column?  tensor(11)


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2sliceing.png" width="500" alt="Example of Matrix Index and Slicing">


In [60]:
# Use tensor_obj[begin_row_number: end_row_number, begin_column_number: end_column number] 
# and tensor_obj[row][begin_column_number: end_column number] to do the slicing

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[0, 0:2])
print("What is the value on 1st-row first two columns? ", tensor_example[0][0:2])

What is the value on 1st-row first two columns?  tensor([11, 12])
What is the value on 1st-row first two columns?  tensor([11, 12])


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2slicing2.png" width="500" alt="Example of Matrix Index and Slicing">


In [61]:
# Use tensor_obj[begin_row_number: end_row_number, begin_column_number: end_column number] 

tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 3rd-column last two rows? ", tensor_example[1:3, 2])

What is the value on 3rd-column last two rows?  tensor([23, 33])


## Modifying Tensors

In [97]:
t = torch.tensor([20, 1, 2, 3, 4])
# Change the value on the index 0 to 100
t[0] = 100
t

tensor([100,   1,   2,   3,   4])

<!-- <h2 id="Tensor_Func">Tensor Functions</h2>
 -->
 ## Tensor Functions


<h3>Mean and Standard Deviation</h3>


In [104]:
math_tensor = torch.tensor([1.0, -1.0, 1, -1])
math_tensor

tensor([ 1., -1.,  1., -1.])

<!--Empty Space for separating topics-->


In [103]:
#Calculate the mean for math_tensor
mean = math_tensor.mean()
mean

tensor(0.)

<!--Empty Space for separating topics-->


In [ ]:
#Calculate the standard deviation for math_tensor
standard_deviation = math_tensor.std()
standard_deviation

<!--Empty Space for separating topics-->


In [105]:
# Sample for introducing max and min methods
max_min_tensor = torch.tensor([1, 1, 3, 5, 5])
max_min_tensor

tensor([1, 1, 3, 5, 5])

In [106]:
# Method for finding the maximum value in the tensor
max_min_tensor.max()

tensor(5)

In [107]:
# Method for finding the minimum value in the tensor
max_min_tensor.min()

tensor(1)

<!-- <h2 id="Tensor_Op">Tensor Operations</h2>
 -->
 ## Tensor Operations


### Tensor Addition, Substraction
- The two tensors must have the same number of dimensions and the same number of elements

In [74]:
# Create two sample tensors
u = torch.tensor([1, 0])
v = torch.tensor([0, 1])

In [108]:
# Add u and v
u + v

tensor([4, 4])

In [109]:
# Substract v from u
u-v

tensor([-2,  0])

### Multiplication and Addition with Scalar

In [77]:
# tensor + scalar
u = torch.tensor([1, 2, 3, -1])
v = u + 1
v

tensor([2, 3, 4, 0])

In [78]:
# tensor * scalar
u = torch.tensor([1, 2])
v = 2 * u
v

tensor([2, 4])

### Tensor Multiplication
- the two tensors must have the same number of dimensions and the same number of elements

In [79]:
# tensor * tensor

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
w = u * v
w

tensor([3, 4])

The result is simply <code>tensor([3, 4])</code>. This result is achieved by multiplying every element in <code>u</code> with the corresponding element in the same position <code>v</code>, which is similar to <i>[1 * 3, 2 * 2]</i>.


### Dot Product

In [80]:
# Calculate dot product of u, v

u = torch.tensor([1, 2])
v = torch.tensor([3, 2])

torch.dot(u,v)

tensor(7)

The result is <code>tensor(7)</code>. The function is <i>1 x 3 + 2 x 2 = 7</i>.


<h3>Tensor Addition</h3>


You can also add tensors; the process is identical to matrix addition. Matrix addition of <b>X</b> and <b>Y</b> is shown in the following figure:


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2add.png" width="500" alt="Tensor Addition in 2D">


In [ ]:
# Calculate [[1, 0], [0, 1]] + [[2, 1], [1, 2]]

X = torch.tensor([[1, 0],[0, 1]]) 
Y = torch.tensor([[2, 1],[1, 2]])
X_plus_Y = X + Y
print(" X + Y: ", X_plus_Y)

<h3> Scalar Multiplication </h3>


Multiplying a tensor by a scalar is identical to multiplying a matrix by a scaler. If you multiply the matrix <b>Y</b> by the scalar 2, you simply multiply every element in the matrix by 2 as shown in the figure:


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2scaller_mult.png" width="500" alt="The product of tensor and scalar">


In [ ]:
# Calculate 2 * [[2, 1], [1, 2]]

Y = torch.tensor([[2, 1], [1, 2]]) 
two_Y = 2 * Y
print("2Y: ", two_Y)

<h3>Element-wise Product/Hadamard Product</h3>


Multiplication of two tensors corresponds to an element-wise product or Hadamard product.  Consider matrix the <b>X</b> and <b>Y</b> **with the same size**. The Hadamard product corresponds to multiplying each of the elements at the same position, that is, multiplying elements with the same color together. The result is a new matrix that is the same size as matrix <b>X</b> and <b>Y</b> as shown in the following figure:


 <a><img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%201/1.2tensor_pruduct.png" width="500" align="center"> </a>


In [28]:
# Calculate [[1, 0], [0, 1]] * [[2, 1], [1, 2]]

X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print("The result of X * Y: ", X_times_Y)

The result of X * Y:  tensor([[2, 0],
        [0, 2]])


<h3>Matrix Multiplication </h3> 

**The number of columns of the matrix on the left side of the multiplication sign must equal to the number of rows of the matrix on the right side.**


First, let us create a tensor <code>X</code> with size 2X3. Then, let us create another tensor <code>Y</code> with size 3X2. Since the number of columns of <code>X</code> is equal to the number of rows of <code>Y</code>. We are able to perform the multiplication.


We use <code>torch.mm()</code> for calculating the multiplication between tensors with different sizes.


In [30]:

A = torch.tensor([[0, 1, 1], [1, 0, 1]])     ## 2 rows, 3 columns
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])  ## 3 rows, 2 columns
A_times_B = torch.mm(A,B)
print("The result of A * B: ", A_times_B)    ## 2 rows, 2 columns

The result of A * B:  tensor([[0, 2],
        [0, 2]])
