<h1>Two-Dimensional Tensors</h1>


In [1]:
# Libraries
import numpy as np 
import matplotlib.pyplot as plt
import torch
import pandas as pd

<!--Empty Space for separating topics-->


#### 1. Convert the following Pandas Dataframe  to a tensor

In [2]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})

t2 = torch.from_numpy(df.values)
t2
# YOUR CODE HERE

tensor([[11,  3],
        [33,  3],
        [22,  2]])

#### 2. Change the values on the second column and the last two rows to 0. 

In [3]:
t = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
t[-2:, 1] = 0
t

# YOUR CODE HERE

tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])

#### 3. Create two tensors with different sizes, and multiply them.
- NB. the tensors must have different dimensions (make sure to choose compatible dimensions and the correct multiplication operation)

In [2]:
## YOUR CODE HERE

In [4]:
a = torch.randn(3, 1)     
b = torch.randn(1, 4)     

result = a * b

In [5]:
result

tensor([[ 1.8356,  1.9439, -0.0586, -0.1471],
        [-0.5438, -0.5759,  0.0173,  0.0436],
        [ 0.7852,  0.8316, -0.0251, -0.0629]])